
spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/securedge?allowPublicKeyRetrieval=true&useSSL=false
    username: rolar
    password: pwd.1024
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

app:
  port: 8080
  root: '/api'
  users: '${app.root}/users'
  accounts: '${app.root}/accounts'
  emailValidationRegEx: '^(.+)@(.+)$'